# Generated by Django 4.2.5 on 2023-09-23 19:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_customeraddress_default_address_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=datetime.datetime(2023, 9, 23, 19, 25, 53, 420311, tzinfo=datetime.timezone.utc), upload_to='uploads/products/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productrating',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Evaluator', to='main.customer'),
        ),
    ]
