# Generated by Django 4.2.5 on 2023-10-18 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='iscustomer',
            new_name='isCustomer',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='isvendor',
            new_name='isVendor',
        ),
    ]
