# Generated by Django 4.2.5 on 2023-10-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_iscustomer_customuser_iscustomer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
