# Generated by Django 4.2.5 on 2023-11-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_productrating_customer_wishlistitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('customer', 'product')},
        ),
    ]
