# Generated by Django 4.2.5 on 2023-11-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_product_image_product_thumbnail_productimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/categories/thumbnail'),
        ),
    ]
