# Generated by Django 4.2.5 on 2023-11-05 22:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_productcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_images',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/products/display_images'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
