# Generated by Django 4.1.6 on 2025-03-01 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_product_product_images_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('purchase_count', models.PositiveIntegerField(default=0)),
                ('cart_add_count', models.PositiveIntegerField(default=0)),
                ('wishlist_add_count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('manual', 'Manually Related'), ('category', 'Same Category'), ('purchased_together', 'Frequently Purchased Together'), ('viewed_together', 'Frequently Viewed Together'), ('recommended', 'System Recommended')], max_length=50)),
                ('relevance_score', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_relations', to='main.product')),
                ('target_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_relations', to='main.product')),
            ],
            options={
                'unique_together': {('source_product', 'target_product')},
            },
        ),
        migrations.CreateModel(
            name='CustomerProductInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('added_to_cart', models.BooleanField(default=False)),
                ('added_to_wishlist', models.BooleanField(default=False)),
                ('purchased', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('interaction_score', models.FloatField(default=0.0)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_interactions', to='main.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_interactions', to='main.product')),
            ],
            options={
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
